version: '3.4'

services:
  mootaeworld:
    image: luckyweb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./public:/usr/src/app/public
